<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
// Testing PHP MAILER
require_once 'PHPMailer/Exception.php';
require_once 'PHPMailer/PHPMailer.php';
require_once 'PHPMailer/SMTP.php';


$mail = new PHPMailer();

// smtp settings
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Host = 'smtp.gmail.com';

$mail->SMTPAuth = true;
$mail->Username = 'ivansunjay04@gmail.com'; //paste one generated by Mailtrap
$mail->Password = 'yozjbryipyolgrfx'; //paste one generated by Mailtrap
$mail->Port = 587;
$mail->SMTPSecure = 'tls';

$mail->isHTML(true);
//from
$mail->setFrom($mail->Username, 'Testing Sumber');
//tujuan
$mail->addAddress('c14220210@john.petra.ac.id');
$mail->Subject = 'PHPMailer GMail SMTP test';
$mail->Body = '<p>Hi, here\'s your invoice...</p>';

if (!$mail->send()) {
    echo "Email Error: " . $mail->ErrorInfo;
    } else {
    echo "Pesan Terkirim!";
    }

?>
